INSERT INTO Provinces(Id, Name) VALUES (1, 'آذربایجان شرقی');
INSERT INTO Provinces(Id, Name) VALUES (2, 'آذربایجان غربی');
INSERT INTO Provinces(Id, Name) VALUES (3, 'اردبیل');
INSERT INTO Provinces(Id, Name) VALUES (4, 'اصفهان');
INSERT INTO Provinces(Id, Name) VALUES (5, 'البرز');
INSERT INTO Provinces(Id, Name) VALUES (6, 'ایلام');
INSERT INTO Provinces(Id, Name) VALUES (7, 'بوشهر');
INSERT INTO Provinces(Id, Name) VALUES (8, 'تهران');
INSERT INTO Provinces(Id, Name) VALUES (9, 'خراسان جنوبی');
INSERT INTO Provinces(Id, Name) VALUES (10, 'خراسان رضوی');
INSERT INTO Provinces(Id, Name) VALUES (11, 'خراسان شمالی');
INSERT INTO Provinces(Id, Name) VALUES (12, 'خوزستان');
INSERT INTO Provinces(Id, Name) VALUES (13, 'زنجان');
INSERT INTO Provinces(Id, Name) VALUES (14, 'سمنان');
INSERT INTO Provinces(Id, Name) VALUES (15, 'سیستان و بلوچستان');
INSERT INTO Provinces(Id, Name) VALUES (16, 'فارس');
INSERT INTO Provinces(Id, Name) VALUES (17, 'قزوین');
INSERT INTO Provinces(Id, Name) VALUES (18, 'قم');
INSERT INTO Provinces(Id, Name) VALUES (19, 'لرستان');
INSERT INTO Provinces(Id, Name) VALUES (20, 'مازندران');
INSERT INTO Provinces(Id, Name) VALUES (21, 'مرکزی');
INSERT INTO Provinces(Id, Name) VALUES (22, 'هرمزگان');
INSERT INTO Provinces(Id, Name) VALUES (23, 'همدان');
INSERT INTO Provinces(Id, Name) VALUES (24, 'چهارمحال و بختیاری');
INSERT INTO Provinces(Id, Name) VALUES (25, 'کردستان');
INSERT INTO Provinces(Id, Name) VALUES (26, 'کرمان');
INSERT INTO Provinces(Id, Name) VALUES (27, 'کرمانشاه');
INSERT INTO Provinces(Id, Name) VALUES (28, 'کهگیلویه و بویراحمد');
INSERT INTO Provinces(Id, Name) VALUES (29, 'گلستان');
INSERT INTO Provinces(Id, Name) VALUES (30, 'گیلان');
INSERT INTO Provinces(Id, Name) VALUES (31, 'یزد');
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (1, 'بستان‌آباد', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (2, 'بناب جدید', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (3, 'تبریز', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (4, 'جلفا', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (5, 'دوزدوزان', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (6, 'زرنق', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (7, 'صوفیان', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (8, 'مراغه', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (9, 'نظرکهریزی', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (10, 'هریس', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (11, 'ورزقان', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (12, 'کلیبر', 1);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (13, 'نالوس', 2);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (14, 'کشاورز', 2);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (15, 'ابی‌بیگلو', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (16, 'اردبیل', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (17, 'اصلاندوز', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (18, 'بیله سوار', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (19, 'تازه‌کندانگوت', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (20, 'جعفرآباد', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (21, 'خلخال', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (22, 'رضی', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (23, 'سرعین', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (24, 'عنبران', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (25, 'لاهرود', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (26, 'مشگین‌شهر', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (27, 'نمین', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (28, 'نیر', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (29, 'هشجین', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (30, 'هیر', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (31, 'پارس‌آباد', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (32, 'کلور', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (33, 'کوراییم', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (34, 'گرمی', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (35, 'گیوی', 3);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (36, 'آران و بیدگل', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (37, 'ابریشم', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (38, 'ابوزیدآباد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (39, 'اردستان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (40, 'اصفهان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (41, 'افوس', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (42, 'انارک', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (43, 'اژیه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (44, 'ایمانشهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (45, 'بادرود', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (46, 'باغ بهادران', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (47, 'برزک', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (48, 'برف انبار', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (49, 'بهاران شهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (50, 'بهارستان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (51, 'بویین و میاندشت', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (52, 'تودشک', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (53, 'تیران', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (54, 'جندق', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (55, 'جوشقان وکامو', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (56, 'حبیب‌آباد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (57, 'حنا', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (58, 'خالدآباد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (59, 'خمینی شهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (60, 'خوانسار', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (61, 'خور', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (62, 'خوراسگان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (63, 'خورزوق', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (64, 'داران', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (65, 'دامنه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (66, 'درچه پیاز', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (67, 'دستگرد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (68, 'دهاقان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (69, 'دهق', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (70, 'دولت‌آباد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (71, 'دیزیچه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (72, 'رزوه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (73, 'رضوانشهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (74, 'زاینده رود', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (75, 'زرین شهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (76, 'زواره', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (77, 'زیباشهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (78, 'سده لنجان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (79, 'سفیدشهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (80, 'سمیرم', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (81, 'سگزی', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (82, 'شاهین شهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (83, 'شهرضا', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (84, 'طالخونچه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (85, 'عسگران', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (86, 'علویچه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (87, 'فریدون‌شهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (88, 'فلاورجان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (89, 'فولادشهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (90, 'قمصر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (91, 'قهدریجان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (92, 'مبارکه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (93, 'مشکات', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (94, 'منظریه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (95, 'مهاباد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (96, 'نایین', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (97, 'نجف‌آباد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (98, 'نصرآباد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (99, 'نطنز', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (100, 'نوش‌آباد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (101, 'نیاسر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (102, 'نیک‌آباد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (103, 'هرند', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (104, 'ورزنه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (105, 'ورنامخواست', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (106, 'وزوان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (107, 'ونک', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (108, 'پیربکران', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (109, 'چادگان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (110, 'چرمهین', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (111, 'چمگردان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (112, 'کاشان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (113, 'کرکوند', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (114, 'کلیشادوسودرجان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (115, 'کمشچه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (116, 'کمه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (117, 'کهریزسنگ', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (118, 'کوشک', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (119, 'کوهپایه', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (120, 'گز', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (121, 'گلدشت', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (122, 'گلشهر', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (123, 'گلپایگان', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (124, 'گوگد', 4);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (125, 'کرج', 5);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (126, 'آبدانان', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (127, 'آسمان‌آباد', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (128, 'ارکواز', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (129, 'ایلام', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (130, 'ایوان', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (131, 'بدره', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (132, 'توحید', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (133, 'دره شهر', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (134, 'دهلران', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (135, 'زرنه', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (136, 'سرابله', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (137, 'لومار', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (138, 'مهران', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (139, 'مورموری', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (140, 'موسیان', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (141, 'میمه', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (142, 'پهله', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (143, 'چوار', 6);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (144, 'آبدان', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (145, 'امام حسن', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (146, 'اهرم', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (147, 'برازجان', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (148, 'بردخون', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (149, 'بندرگناوه', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (150, 'بنک', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (151, 'بوشهر', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (152, 'تنگ ارم', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (153, 'جم', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (154, 'خارک', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (155, 'خورموج', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (156, 'دالکی', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (157, 'دلوار', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (158, 'ریز', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (159, 'سعدآباد', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (160, 'شبانکاره', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (161, 'طاهری', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (162, 'عسلویه', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (163, 'نخل تقی', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (164, 'وحدتیه', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (165, 'چغادک', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (166, 'کاکی', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (167, 'کلمه', 7);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (168, 'آبسرد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (169, 'آبعلی', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (170, 'ارجمند', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (171, 'اسلامشهر', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (172, 'اشتهارد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (173, 'اندیشه', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (174, 'باغستان', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (175, 'باقرشهر', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (176, 'بومهن', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (177, 'تجریش', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (178, 'تهران', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (179, 'جوادآباد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (180, 'حسن‌آباد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (181, 'دماوند', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (182, 'رودهن', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (183, 'ری', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (184, 'شاهدشهر', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (185, 'شریف‌آباد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (186, 'شهرجدیدهشتگرد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (187, 'شهریار', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (188, 'صالح‌آباد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (189, 'صباشهر', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (190, 'صفادشت', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (191, 'طالقان', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (192, 'فردوسیه', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (193, 'فشم', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (194, 'فیروزکوه', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (195, 'قدس', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (196, 'قرچک', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (197, 'لواسان', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (198, 'ماهدشت', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (199, 'محمدشهر', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (200, 'مشکین دشت', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (201, 'ملارد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (202, 'نسیم شهر', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (203, 'نصیرآباد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (204, 'نظرآباد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (205, 'هشتگرد', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (206, 'وحیدیه', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (207, 'ورامین', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (208, 'پاکدشت', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (209, 'پردیس', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (210, 'پیشوا', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (211, 'چهارباغ', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (212, 'چهاردانگه', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (213, 'کمال شهر', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (214, 'کهریزک', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (215, 'کوهسار', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (216, 'کیلان', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (217, 'گرمدره', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (218, 'گلستان', 8);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (219, 'آرین‌شهر', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (220, 'اسدیه', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (221, 'اسفدن', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (222, 'اسلامیه', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (223, 'ایسک', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (224, 'بشرویه', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (225, 'بیرجند', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (226, 'حاجی‌آباد', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (227, 'خضری دشت بیاض', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (228, 'خوسف', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (229, 'زهان', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (230, 'سرایان', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (231, 'سربیشه', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (232, 'سه قلعه', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (233, 'شوسف', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (234, 'فردوس', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (235, 'قاین', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (236, 'مود', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (237, 'نهبندان', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (238, 'نیمبلوک', 9);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (239, 'باجگیران', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (240, 'باخرز', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (241, 'بجستان', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (242, 'بردسکن', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (243, 'بیدخت', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (244, 'تایباد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (245, 'تربت جام', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (246, 'تربت حیدریه', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (247, 'جغتای', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (248, 'جنگل', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (249, 'خرو', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (250, 'خلیل‌آباد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (251, 'خواف', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (252, 'داورزن', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (253, 'درود', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (254, 'درگز', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (255, 'رباط سنگ', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (256, 'رشتخوار', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (257, 'رضویه', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (258, 'روداب', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (259, 'ریوش', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (260, 'سبزوار', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (261, 'سرخس', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (262, 'سفیدسنگ', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (263, 'سلامی', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (264, 'سلطان‌آباد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (265, 'سنگان', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (266, 'شاندیز', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (267, 'ششتمد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (268, 'شهرزو', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (269, 'طرقبه', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (270, 'فرهادگرد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (271, 'فریمان', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (272, 'فیروزه', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (273, 'فیض‌آباد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (274, 'قاسم‌آباد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (275, 'قدمگاه', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (276, 'قلندرآباد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (277, 'قوچان', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (278, 'لطف‌آباد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (279, 'مزداوند', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (280, 'مشهد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (281, 'مشهدریزه', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (282, 'ملک‌آباد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (283, 'نشتیفان', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (284, 'نقاب', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (285, 'نوخندان', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (286, 'نیشابور', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (287, 'نیل شهر', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (288, 'چاپشلو', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (289, 'چناران', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (290, 'چکنه', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (291, 'کاخک', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (292, 'کاریز', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (293, 'کاشمر', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (294, 'کدکن', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (295, 'کلات', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (296, 'کندر', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (297, 'گناباد', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (298, 'یونسی', 10);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (299, 'آشخانه', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (300, 'اسفراین', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (301, 'بجنورد', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (302, 'حصارگرمخان', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (303, 'درق', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (304, 'راز', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (305, 'سنخواست', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (306, 'شوقان', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (307, 'شیروان', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (308, 'صفی‌آباد', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (309, 'فاروج', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (310, 'قاضی', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (311, 'لوجلی', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (312, 'پیش قلعه', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (313, 'گرمه جاجرم', 11);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (314, 'آبادان', 12);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (315, 'بندرامام خمینی', 12);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (316, 'بهبهان', 12);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (317, 'خرمشهر', 12);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (318, 'دهدز', 12);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (319, 'شوش', 12);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (320, 'لالی', 12);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (321, 'آب‌بر', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (322, 'ابهر', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (323, 'حلب', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (324, 'خرمدره', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (325, 'دندی', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (326, 'زرین رود', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (327, 'زرین‌آباد', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (328, 'زنجان', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (329, 'سجاس', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (330, 'سلطانیه', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (331, 'صایین‌قلعه', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (332, 'قیدار', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (333, 'ماه نشان', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (334, 'هیدج', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (335, 'چورزق', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (336, 'گرماب', 13);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (337, 'آرادان', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (338, 'امیریه', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (339, 'ایوانکی', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (340, 'بسطام', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (341, 'بیارجمند', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (342, 'دامغان', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (343, 'دیباج', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (344, 'سرخه', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (345, 'سمنان', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (346, 'شاهرود', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (347, 'شهمیرزاد', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (348, 'مجن', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (349, 'مهدی شهر', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (350, 'میامی', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (351, 'کلاته خیج', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (352, 'گرمسار', 14);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (353, 'ادیمی', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (354, 'اسپکه', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (355, 'ایرانشهر', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (356, 'بزمان', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (357, 'بمپور', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (358, 'بنت', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (359, 'بنجار', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (360, 'جالق', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (361, 'خاش', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (362, 'دوست محمد', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (363, 'راسک', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (364, 'زابل', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (365, 'زابلی', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (366, 'زاهدان', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (367, 'زهک', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (368, 'سراوان', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (369, 'سرباز', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (370, 'سوران', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (371, 'سیرکان', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (372, 'فنوج', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (373, 'قصرقند', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (374, 'محمدآباد', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (375, 'میرجاوه', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (376, 'نصرت‌آباد', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (377, 'نوک‌آباد', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (378, 'نگور', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (379, 'نیک شهر', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (380, 'پیشین', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (381, 'کنارک', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (382, 'گلمورتی', 15);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (383, 'آباده', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (384, 'آباده طشک', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (385, 'ارسنجان', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (386, 'استهبان', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (387, 'اشکنان', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (388, 'افزر', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (389, 'اقلید', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (390, 'اهل', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (391, 'اوز', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (392, 'ایج', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (393, 'ایزدخواست', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (394, 'باب انار', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (395, 'بالاده', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (396, 'بنارویه', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (397, 'بهمن', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (398, 'بوانات', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (399, 'بیرم', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (400, 'بیضا', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (401, 'جنت شهر', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (402, 'جهرم', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (403, 'جویم', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (404, 'خاوران', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (405, 'خرامه', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (406, 'خشت', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (407, 'خنج', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (408, 'داراب', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (409, 'داریان', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (410, 'دبیران', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (411, 'دهستان نوبندگان', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (412, 'رونیز', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (413, 'زاهدشهر', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (414, 'زرقان', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (415, 'سده', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (416, 'سروستان', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (417, 'سعادت شهر', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (418, 'سورمق', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (419, 'سیدان', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (420, 'ششده', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (421, 'شهرپیر', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (422, 'شیراز', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (423, 'صغاد', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (424, 'صفاشهر', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (425, 'علامرودشت', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (426, 'فراشبند', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (427, 'فسا', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (428, 'فیروزآباد', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (429, 'قادرآباد', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (430, 'قایمیه', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (431, 'قطب‌آباد', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (432, 'قیر', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (433, 'لار', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (434, 'لامرد', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (435, 'لپویی', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (436, 'مرودشت', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (437, 'مشکان', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (438, 'مصیری', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (439, 'مهر', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (440, 'میمند', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (441, 'نودان', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (442, 'نی ریز', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (443, 'وراوی', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (444, 'کازرون', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (445, 'کامفیروز', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (446, 'کنارتخته', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (447, 'کوار', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (448, 'گراش', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (449, 'گله دار', 16);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (450, 'آبگرم', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (451, 'آبیک', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (452, 'ارداق', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (453, 'اسفرورین', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (454, 'اقبالیه', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (455, 'الوند', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (456, 'اوج', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (457, 'بویین زهرا', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (458, 'بیدستان', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (459, 'تاکستان', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (460, 'خاکعلی', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (461, 'خرمدشت', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (462, 'دانسفهان', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (463, 'رازمیان', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (464, 'سگزآباد', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (465, 'سیردان', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (466, 'شال', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (467, 'قزوین', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (468, 'محمدیه', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (469, 'محمودآبادنمونه', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (470, 'معلم کلایه', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (471, 'نرجه', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (472, 'کوهین', 17);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (473, 'جعفریه', 18);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (474, 'دستجرد', 18);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (475, 'قم', 18);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (476, 'قنوات', 18);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (477, 'کهک', 18);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (478, 'ازنا', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (479, 'اشترینان', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (480, 'الشتر', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (481, 'الیگودرز', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (482, 'بروجرد', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (483, 'خرم‌آباد', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (484, 'درب گنبد', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (485, 'دورود', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (486, 'زاغه', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (487, 'سراب دوره', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (488, 'سپیددشت', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (489, 'محمودوند', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (490, 'معمولان', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (491, 'نورآباد', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (492, 'پلدختر', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (493, 'چالانچولان', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (494, 'چغلوندی', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (495, 'چقابل', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (496, 'کونانی', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (497, 'کوهدشت', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (498, 'گراب', 19);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (499, 'بهنمیر', 20);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (500, 'ساری', 20);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (501, 'کله بست', 20);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (502, 'کیاسر', 20);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (503, 'آبش احمد', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (504, 'آستارا', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (505, 'آشتیان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (506, 'آلاشت', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (507, 'ابپخش', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (508, 'احمد سرگوراب', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (509, 'اراک', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (510, 'ارومیه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (511, 'اروندکنار', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (512, 'ازگله', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (513, 'اسالم', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (514, 'اسلام‌آباد غرب', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (515, 'اسکو', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (516, 'اطاقور', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (517, 'الوان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (518, 'امل', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (519, 'اندیمشک', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (520, 'اهر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (521, 'اواجیق', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (522, 'ایذه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (523, 'ایلخچی', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (524, 'بابل', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (525, 'بابلسر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (526, 'باروق', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (527, 'بازرگان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (528, 'بستان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (529, 'بلده', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (530, 'بناب', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (531, 'بندر جاسک', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (532, 'بندر دیر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (533, 'بندر ریگ', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (534, 'بندر ماهشهر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (535, 'بندرانزلی', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (536, 'بهشهر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (537, 'تازه شهر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (538, 'تازه‌آباد', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (539, 'تسوج', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (540, 'تفرش', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (541, 'توره', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (542, 'تکاب', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (543, 'تیکمه داش', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (544, 'جایزان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (545, 'جویبار', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (546, 'جیرنده', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (547, 'حر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (548, 'حسینیه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (549, 'حمیدیه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (550, 'حویق', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (551, 'خاروانا', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (552, 'خراجو', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (553, 'خشکبیجار', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (554, 'خلیل شهر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (555, 'خمارلو', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (556, 'خمام', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (557, 'خمین', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (558, 'خنداب', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (559, 'خوی', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (560, 'دابودشت', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (561, 'داودآباد', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (562, 'دلیجان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (563, 'دیلمان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (564, 'رازقان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (565, 'رامشیر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (566, 'رامهرمز', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (567, 'رانکوه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (568, 'رباط', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (569, 'ربط', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (570, 'رستمکلا', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (571, 'رفیع', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (572, 'رودبنه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (573, 'رودسر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (574, 'رویان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (575, 'رینه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (576, 'زرگر محله', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (577, 'زنوز', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (578, 'سالند', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (579, 'سرخرود', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (580, 'سردرود', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (581, 'سلماس', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (582, 'سلمان شهر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (583, 'سنجان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (584, 'سنقر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (585, 'سنگر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (586, 'سورک', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (587, 'سوسنگرد', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (588, 'سومار', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (589, 'سیس', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (590, 'سیلوانه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (591, 'سیمینه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (592, 'شازند', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (593, 'شاهین‌دژ', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (594, 'شندآباد', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (595, 'شوشتر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (596, 'شوط', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (597, 'شیبان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (598, 'شیرگاه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (599, 'صیدون', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (600, 'عباس‌آباد', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (601, 'فرادنبه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (602, 'فرمهین', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (603, 'فریم', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (604, 'فومن', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (605, 'فیرورق', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (606, 'قره ضیاءالدین', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (607, 'قره‌آغاج', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (608, 'قصرشیرین', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (609, 'قورچی باشی', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (610, 'لنگرود', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (611, 'لوشان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (612, 'لیسار', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (613, 'مامونیه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (614, 'مجلسی', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (615, 'محلات', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (616, 'محمدیار', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (617, 'محمودآباد', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (618, 'مراوه تپه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (619, 'مرجقل', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (620, 'مرزن‌آباد', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (621, 'ملکان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (622, 'ممقان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (623, 'مهاجران', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (624, 'مهربان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (625, 'میان راهان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (626, 'میاندواب', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (627, 'میلاجرد', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (628, 'نراق', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (629, 'نوبران', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (630, 'نودشه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (631, 'نوسود', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (632, 'نوشهر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (633, 'نوشین', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (634, 'هشترود', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (635, 'هفتگل', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (636, 'هندودر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (637, 'هندیجان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (638, 'هوراند', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (639, 'هویزه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (640, 'واجارگاه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (641, 'وایقان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (642, 'پاوه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (643, 'پرند', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (644, 'پل سفید', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (645, 'پلدشت', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (646, 'پیرانشهر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (647, 'چالوس', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (648, 'چمران', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (649, 'چهاربرج', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (650, 'چوبر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (651, 'کارزین', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (652, 'کتالم وسادات شهر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (653, 'کرهرود', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (654, 'کشکسرای', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (655, 'کلاردشت', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (656, 'کلوانق', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (657, 'کمیجان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (658, 'کوزه کنان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (659, 'کومله', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (660, 'کوچصفهان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (661, 'کیاشهر', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (662, 'گتوند', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (663, 'گردکشانه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (664, 'گزنک', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (665, 'گلوگاه', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (666, 'گهواره', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (667, 'گوگان', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (668, 'گیلانغرب', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (669, 'یامچی', 21);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (670, 'ابوموسی', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (671, 'بستک', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (672, 'بندر لنگه', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (673, 'بندرعباس', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (674, 'جناح', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (675, 'خمیر', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (676, 'درگهان', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (677, 'دهبارز', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (678, 'رودان', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (679, 'زیارتعلی', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (680, 'سوزا', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (681, 'سیریک', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (682, 'فارغان', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (683, 'فین', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (684, 'قشم', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (685, 'میناب', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (686, 'هرمز', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (687, 'کنگ', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (688, 'کیش', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (689, 'گاوبندی', 22);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (690, 'ازندریان', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (691, 'اسدآباد', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (692, 'برزول', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (693, 'بهار', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (694, 'تویسرکان', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (695, 'جورقان', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (696, 'جوکار', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (697, 'دمق', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (698, 'رزن', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (699, 'زنگنه', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (700, 'سامن', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (701, 'سرکان', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (702, 'شیرین سو', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (703, 'فامنین', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (704, 'فرسفج', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (705, 'فیروزان', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (706, 'قهاوند', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (707, 'لالجین', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (708, 'مریانج', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (709, 'ملایر', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (710, 'نهاوند', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (711, 'همدان', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (712, 'کبودراهنگ', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (713, 'گل تپه', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (714, 'گیان', 23);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (715, 'اردل', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (716, 'الونی', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (717, 'باباحیدر', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (718, 'بروجن', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (719, 'بلداجی', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (720, 'بن (شهرکرد)', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (721, 'جونقان', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (722, 'سامان', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (723, 'سفیددشت', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (724, 'سودجان', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (725, 'سورشجان', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (726, 'شلمزار', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (727, 'شهرکرد', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (728, 'طاقانک', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (729, 'فارسان', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (730, 'فرخ شهر', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (731, 'لردگان', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (732, 'مال خلیفه', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (733, 'ناغان', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (734, 'نافچ', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (735, 'هفشجان', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (736, 'چلگرد', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (737, 'کیان', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (738, 'گندمان', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (739, 'گهرو', 24);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (740, 'ارمرده', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (741, 'بابارشانی', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (742, 'بانه', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (743, 'بویین سفلی', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (744, 'بیجار', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (745, 'دزج', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (746, 'دلبران', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (747, 'دهگلان', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (748, 'دیواندره', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (749, 'زرینه', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (750, 'سروآباد', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (751, 'سریش‌آباد', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (752, 'سقز', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (753, 'سنندج', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (754, 'شویشه', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (755, 'صاحب', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (756, 'قروه', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (757, 'مریوان', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (758, 'موچش', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (759, 'چناره', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (760, 'کامیاران', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (761, 'کانی سور', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (762, 'یاسوکند', 25);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (763, 'اختیارآباد', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (764, 'ارزوییه', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (765, 'انار', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (766, 'اندوهجرد', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (767, 'باغین', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (768, 'بافت', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (769, 'بردسیر', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (770, 'بروات', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (771, 'بزنجان', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (772, 'بم', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (773, 'بهرمان', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (774, 'جبالبارز', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (775, 'جوپار', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (776, 'جیرفت', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (777, 'حسین‌آباد', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (778, 'خانوک', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (779, 'درب بهشت', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (780, 'دهج', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (781, 'رابر', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (782, 'راور', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (783, 'راین', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (784, 'رفسنجان', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (785, 'رودبار', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (786, 'زرند', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (787, 'زنگی‌آباد', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (788, 'زیدآباد', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (789, 'سیرجان', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (790, 'شهداد', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (791, 'شهربابک', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (792, 'عنبرآباد', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (793, 'فاریاب', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (794, 'فهرج', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (795, 'قلعه گنج', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (796, 'ماهان', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (797, 'محی‌آباد', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (798, 'مردهک', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (799, 'مس سرچشمه', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (800, 'منوجان', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (801, 'نجف شهر', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (802, 'نرماشیر', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (803, 'نظام شهر', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (804, 'نودژ', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (805, 'نگار', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (806, 'هجدک', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (807, 'پاریز', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (808, 'چترود', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (809, 'کاظم‌آباد', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (810, 'کرمان', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (811, 'کشکوییه', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (812, 'کهنوج', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (813, 'کوهبنان', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (814, 'کیانشهر', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (815, 'گلباف', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (816, 'گلزار', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (817, 'یزدان شهر', 26);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (818, 'بیستون', 27);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (819, 'روانسر', 27);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (820, 'سرپل ذهاب', 27);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (821, 'هرسین', 27);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (822, 'کرمانشاه', 27);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (823, 'باشت', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (824, 'دهدشت', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (825, 'دوگنبدان', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (826, 'دیشموک', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (827, 'سوق', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (828, 'سی سخت', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (829, 'قلعه رییسی', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (830, 'لنده', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (831, 'لیکک', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (832, 'مارگون', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (833, 'چرام', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (834, 'گراب سفلی', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (835, 'یاسوج', 28);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (836, 'آزادشهر', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (837, 'آق‌قلا', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (838, 'انبارالوم', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (839, 'اینچه برون', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (840, 'بندر گز', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (841, 'خان ببین', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (842, 'دلند', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (843, 'رامیان', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (844, 'سرخنکلاته', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (845, 'سیمین شهر', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (846, 'علی‌آباد', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (847, 'فاضل‌آباد', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (848, 'مینودشت', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (849, 'نوده خاندوز', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (850, 'نوکنده', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (851, 'نگین شهر', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (852, 'کردکوی', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (853, 'کلاله', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (854, 'گالیکش', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (855, 'گرگان', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (856, 'گمیش تپه', 29);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (857, 'آذرشهر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (858, 'آستانه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (859, 'آستانه اشرفیه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (860, 'آغاجاری', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (861, 'آن‌ابد', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (862, 'اشنویه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (863, 'اقکند', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (864, 'املش', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (865, 'امیدیه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (866, 'امیرکلا', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (867, 'اهواز', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (868, 'ایزدشهر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (869, 'ایواوغلی', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (870, 'بازارجمعه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (871, 'باسمنج', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (872, 'باغملک', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (873, 'باینگان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (874, 'بایگ', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (875, 'بخشایش', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (876, 'بره سر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (877, 'بندر ترکمن', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (878, 'بندر دیلم', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (879, 'بندر چارک', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (880, 'بندر کنگان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (881, 'بوکان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (882, 'ترک', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (883, 'ترکمانچای', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (884, 'تنکابن', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (885, 'توتکابن', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (886, 'جوانرود', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (887, 'حمیل', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (888, 'خامنه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (889, 'خسروشهر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (890, 'خواجه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (891, 'خوش رودپی', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (892, 'دزاب', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (893, 'دزفول', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (894, 'رامسر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (895, 'رباط کریم', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (896, 'رحیم‌آباد', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (897, 'رستم‌آباد', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (898, 'رشت', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (899, 'ریحان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (900, 'زاویه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (901, 'زهره', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (902, 'زیراب', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (903, 'ساوه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (904, 'سراب', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (905, 'سردشت', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (906, 'سرمست', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (907, 'سرو', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (908, 'سطر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (909, 'سیاهکل', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (910, 'سیه رود', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (911, 'سیه چشمه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (912, 'شادگان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (913, 'شبستر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (914, 'شربیان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (915, 'شرفخانه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (916, 'شفت', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (917, 'شلمان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (918, 'صحنه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (919, 'صومعه سرا', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (920, 'ضیاءآباد', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (921, 'عجب شیر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (922, 'غرق‌آباد', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (923, 'فریدونکنار', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (924, 'قائم‌شهر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (925, 'قروه در جزین', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (926, 'قلعه تل', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (927, 'قلعه خواجه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (928, 'قوشچی', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (929, 'لاهیجان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (930, 'لشت نشا', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (931, 'لوندویل', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (932, 'لیلان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (933, 'مؤمن‌آباد', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (934, 'ماسال', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (935, 'ماسوله', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (936, 'ماکو', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (937, 'مرزیکلا', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (938, 'مرند', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (939, 'مسجد سلیمان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (940, 'مقاومت', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (941, 'ملاثانی', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (942, 'منجیل', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (943, 'میانرود', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (944, 'میانه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (945, 'میرآباد', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (946, 'مینوشهر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (947, 'نشتارود', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (948, 'نقده', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (949, 'نور', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (950, 'نکا', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (951, 'نیمور', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (952, 'هادیشهر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (953, 'هشتپر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (954, 'هلشی', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (955, 'هیدوج', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (956, 'ویس', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (957, 'پرندک', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (958, 'پره سر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (959, 'چابهار', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (960, 'چابکسر', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (961, 'چمستان', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (962, 'کرندغرب', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (963, 'کره‌ای', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (964, 'کلارآباد', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (965, 'کلاچای', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (966, 'کنگاور', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (967, 'کوزران', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (968, 'کوهی خیل', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (969, 'کیاکلا', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (970, 'گتاب', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (971, 'گلوگاه', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (972, 'گنبد کاووس', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (973, 'گوراب زرمیخ', 30);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (974, 'ابرکوه', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (975, 'احمدآباد', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (976, 'اردکان', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (977, 'اشکذر', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (978, 'بافق', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (979, 'به‌آباد', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (980, 'تفت', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (981, 'حمیدیا', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (982, 'خضرآباد', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (983, 'دیهوک', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (984, 'زارچ', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (985, 'شاهدیه', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (986, 'طبس', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (987, 'عشق‌آباد', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (988, 'عقدا', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (989, 'مروست', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (990, 'مهردشت', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (991, 'مهریز', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (992, 'میبد', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (993, 'ندوشن', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (994, 'هرات', 31);
INSERT INTO Cities(Id, Name, ProvinceId) VALUES (995, 'یزد', 31);